name: beta
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: update beta
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: | 
            cd ${{ secrets.WWWROOT }}
            if ! [ -d releases-${{ secrets.URL }} ]; then mkdir releases-${{ secrets.URL }}; fi;
            NOW=$(date +%d%m%y%H%M)
            git clone https://github.com/PKNW1PLEX/${{ secrets.URL }}.git releases-${{ secrets.URL }}/$NOW #(date +%d%m%y%H%M)
            if [ -f beta.${{ secrets.URL }} ]; then rm beta.${{ secrets.URL }}; fi
            ln -s releases-${{ secrets.URL }}/$NOW beta.${{ secrets.URL }}
          host: ${{ secrets.KS2_HOST }}
          port: ${{ secrets.KS2_PORT }}
          username: ${{ secrets.KS2_USER }}
          privateKey: ${{ secrets.KS2_PRIVATE_KEY}}
