name: beta
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: update beta
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: | 
            cd ${{ secrets.WWWROOT }}
            if ! [ -d releases-${{ secrets.URL }} ]; then mkdir releases-${{ secrets.URL }}; fi
            git clone https://github.com/$GITHUB_REPOSITORY releases-${{ secrets.URL }}/$(date +%d%m%y%H%M)
          host: ${{ secrets.KS2_HOST }}
          port: ${{ secrets.KS2_PORT }}
          username: ${{ secrets.KS2_USER }}
          privateKey: ${{ secrets.KS2_PRIVATE_KEY}}
